#############################################################################
# Makefile for building: albatross-display
# Generated by qmake (1.07a) (Qt 3.3.6) on: Tue Sep  1 12:27:01 2009
# Project:  albatross-display.pro
# Template: app
# Command: $(QMAKE) -o Makefile albatross-display.pro
#############################################################################

####### Compiler, tools and options

CC       = gcc
CXX      = g++
LEX      = flex
YACC     = yacc
CFLAGS   = -pipe -Wall -W -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m32 -march=i386 -mtune=generic -fasynchronous-unwind-tables  -DQT_NO_DEBUG -DQT_SHARED -DQT_THREAD_SUPPORT
CXXFLAGS = -pipe -Wall -W -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m32 -march=i386 -mtune=generic -fasynchronous-unwind-tables  -DQT_NO_DEBUG -DQT_SHARED -DQT_THREAD_SUPPORT
LEXFLAGS = 
YACCFLAGS= -d
INCPATH  = -I/usr/lib/qt-3.3/mkspecs/default -I. -I. -ICommonFiles -I$(QTDIR)/include
LINK     = g++
LFLAGS   = 
LIBS     = $(SUBLIBS) -L$(QTDIR)/lib -lqt-mt -lXext -lX11 -lm
AR       = ar cqs
RANLIB   = 
MOC      = $(QTDIR)/bin/moc
UIC      = $(QTDIR)/bin/uic
QMAKE    = qmake
TAR      = tar -cf
GZIP     = gzip -9f
COPY     = cp -f
COPY_FILE= $(COPY)
COPY_DIR = $(COPY) -r
INSTALL_FILE= $(COPY_FILE)
INSTALL_DIR = $(COPY_DIR)
DEL_FILE = rm -f
SYMLINK  = ln -sf
DEL_DIR  = rmdir
MOVE     = mv -f
CHK_DIR_EXISTS= test -d
MKDIR    = mkdir -p

####### Output directory

OBJECTS_DIR = ./

####### Files

HEADERS = Ades.ui.h \
		ArcTyp.ui.h \
		AsdApp.h \
		AsdMenu.h \
		AsdView.h \
		Assr.ui.h \
		Asterix.h \
		AsyncSocket.h \
		Brightness.ui.h \
		ChangePassword.ui.h \
		ClientSocket.h \
		ColorMngr.h \
		CommonDataTypes.h \
		CouplingMngr.h \
		CustomSetDialog.ui.h \
		DataMngr.h \
		DisplayElement.h \
		Elements.h \
		FindTrackDlg.ui.h \
		FlightPlan.h \
		FlSelect.ui.h \
		FlSelectOther.ui.h \
		FontMngr.h \
		Geo.h \
		HeightFilterDlg.ui.h \
		ImportantTrack.h \
		InfoMngr.h \
		Interface.h \
		LineView.h \
		resource.h \
		Runway.ui.h \
		RwdView.h \
		SafetyEventHandler.h \
		SaveAs.ui.h \
		SetupMngr.h \
		SignIn.ui.h \
		SKMessageBox.h \
		StatusBar.h \
		StdAfx.h \
		String.h \
		SystemInfo.ui.h \
		SystemMode.h \
		TimeWnd.h \
		TopLevel.h \
		Track.h \
		TrackControl.ui.h \
		TrackList.h \
		Tssr.ui.h \
		TssrOther.ui.h \
		UserMngr.h \
		View.h \
		VisuMap.h \
		VisuSocket.h \
		WdwMngr.h \
		WfAttrib.h \
		WinHints.h \
		Wtc.ui.h \
		CommonFiles/CDirectoryFileOperations.h \
		CommonFiles/CommonMenu.h \
		CommonFiles/CommonObject.h \
		CommonFiles/Files.h \
		CommonFiles/GraphicSymbol.h \
		CommonFiles/HWFile.h \
		CommonFiles/IniFile.h \
		CommonFiles/IPAddressValidator.h \
		CommonFiles/Templ.h \
		CommonFiles/VersionNumberValidator.h
SOURCES = AsdApp.cpp \
		AsdMenu.cpp \
		AsdView.cpp \
		Asterix.cpp \
		AsyncSocket.cpp \
		ClientSocket.cpp \
		ColorMngr.cpp \
		CommonDataTypes.cpp \
		CouplingMngr.cpp \
		DataMngr.cpp \
		Elements.cpp \
		FlightPlan.cpp \
		FontMngr.cpp \
		Geo.cpp \
		ImportantTrack.cpp \
		InfoMngr.cpp \
		Interface.cpp \
		LineView.cpp \
		Main.cpp \
		RwdView.cpp \
		SafetyEventHandler.cpp \
		SetupMngr.cpp \
		SKMessageBox.cpp \
		StatusBar.cpp \
		String.cpp \
		SystemMode.cpp \
		TimeWnd.cpp \
		TopLevel.cpp \
		Track.cpp \
		TrackList.cpp \
		UserMngr.cpp \
		View.cpp \
		VisuMap.cpp \
		VisuSocket.cpp \
		WdwMngr.cpp \
		WfAttrib.cpp \
		WinHints.cpp \
		CommonFiles/CDirectoryFileOperations.cpp \
		CommonFiles/CommonMenu.cpp \
		CommonFiles/CommonObject.cpp \
		CommonFiles/Files.cpp \
		CommonFiles/GraphicSymbol.cpp \
		CommonFiles/HWFile.cpp \
		CommonFiles/IniFile.cpp \
		CommonFiles/IPAddressValidator.cpp \
		CommonFiles/VersionNumberValidator.cpp
OBJECTS = AsdApp.o \
		AsdMenu.o \
		AsdView.o \
		Asterix.o \
		AsyncSocket.o \
		ClientSocket.o \
		ColorMngr.o \
		CommonDataTypes.o \
		CouplingMngr.o \
		DataMngr.o \
		Elements.o \
		FlightPlan.o \
		FontMngr.o \
		Geo.o \
		ImportantTrack.o \
		InfoMngr.o \
		Interface.o \
		LineView.o \
		Main.o \
		RwdView.o \
		SafetyEventHandler.o \
		SetupMngr.o \
		SKMessageBox.o \
		StatusBar.o \
		String.o \
		SystemMode.o \
		TimeWnd.o \
		TopLevel.o \
		Track.o \
		TrackList.o \
		UserMngr.o \
		View.o \
		VisuMap.o \
		VisuSocket.o \
		WdwMngr.o \
		WfAttrib.o \
		WinHints.o \
		CDirectoryFileOperations.o \
		CommonMenu.o \
		CommonObject.o \
		Files.o \
		GraphicSymbol.o \
		HWFile.o \
		IniFile.o \
		IPAddressValidator.o \
		VersionNumberValidator.o \
		Ades.o \
		ArcTyp.o \
		Assr.o \
		Brightness.o \
		ChangePassword.o \
		CustomSetDialog.o \
		FindTrackDlg.o \
		FlSelect.o \
		FlSelectOther.o \
		HeightFilterDlg.o \
		Runway.o \
		SaveAs.o \
		SignIn.o \
		SystemInfo.o \
		TrackControl.o \
		Tssr.o \
		TssrOther.o \
		Wtc.o
FORMS = Ades.ui \
		ArcTyp.ui \
		Assr.ui \
		Brightness.ui \
		ChangePassword.ui \
		CustomSetDialog.ui \
		FindTrackDlg.ui \
		FlSelect.ui \
		FlSelectOther.ui \
		HeightFilterDlg.ui \
		Runway.ui \
		SaveAs.ui \
		SignIn.ui \
		SystemInfo.ui \
		TrackControl.ui \
		Tssr.ui \
		TssrOther.ui \
		Wtc.ui
UICDECLS = Ades.h \
		ArcTyp.h \
		Assr.h \
		Brightness.h \
		ChangePassword.h \
		CustomSetDialog.h \
		FindTrackDlg.h \
		FlSelect.h \
		FlSelectOther.h \
		HeightFilterDlg.h \
		Runway.h \
		SaveAs.h \
		SignIn.h \
		SystemInfo.h \
		TrackControl.h \
		Tssr.h \
		TssrOther.h \
		Wtc.h
UICIMPLS = Ades.cpp \
		ArcTyp.cpp \
		Assr.cpp \
		Brightness.cpp \
		ChangePassword.cpp \
		CustomSetDialog.cpp \
		FindTrackDlg.cpp \
		FlSelect.cpp \
		FlSelectOther.cpp \
		HeightFilterDlg.cpp \
		Runway.cpp \
		SaveAs.cpp \
		SignIn.cpp \
		SystemInfo.cpp \
		TrackControl.cpp \
		Tssr.cpp \
		TssrOther.cpp \
		Wtc.cpp
SRCMOC   = moc_AsyncSocket.cpp \
		moc_ImportantTrack.cpp \
		moc_LineView.cpp \
		moc_TopLevel.cpp \
		moc_View.cpp \
		moc_Ades.cpp \
		moc_ArcTyp.cpp \
		moc_Assr.cpp \
		moc_Brightness.cpp \
		moc_ChangePassword.cpp \
		moc_CustomSetDialog.cpp \
		moc_FindTrackDlg.cpp \
		moc_FlSelect.cpp \
		moc_FlSelectOther.cpp \
		moc_HeightFilterDlg.cpp \
		moc_Runway.cpp \
		moc_SaveAs.cpp \
		moc_SignIn.cpp \
		moc_SystemInfo.cpp \
		moc_TrackControl.cpp \
		moc_Tssr.cpp \
		moc_TssrOther.cpp \
		moc_Wtc.cpp
OBJMOC = moc_AsyncSocket.o \
		moc_ImportantTrack.o \
		moc_LineView.o \
		moc_TopLevel.o \
		moc_View.o \
		moc_Ades.o \
		moc_ArcTyp.o \
		moc_Assr.o \
		moc_Brightness.o \
		moc_ChangePassword.o \
		moc_CustomSetDialog.o \
		moc_FindTrackDlg.o \
		moc_FlSelect.o \
		moc_FlSelectOther.o \
		moc_HeightFilterDlg.o \
		moc_Runway.o \
		moc_SaveAs.o \
		moc_SignIn.o \
		moc_SystemInfo.o \
		moc_TrackControl.o \
		moc_Tssr.o \
		moc_TssrOther.o \
		moc_Wtc.o
DIST	   = albatross-display.pro
QMAKE_TARGET = albatross-display
DESTDIR  = 
TARGET   = albatross-display

first: all
####### Implicit rules

.SUFFIXES: .c .o .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o $@ $<

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(UICDECLS) $(OBJECTS) $(OBJMOC)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJMOC) $(OBJCOMP) $(LIBS)

mocables: $(SRCMOC)
uicables: $(UICDECLS) $(UICIMPLS)

$(MOC): 
	( cd $(QTDIR)/src/moc && $(MAKE) )

Makefile: albatross-display.pro  /usr/lib/qt-3.3/mkspecs/default/qmake.conf /usr/lib/qt-3.3/lib/libqt-mt.prl
	$(QMAKE) -o Makefile albatross-display.pro
qmake: 
	@$(QMAKE) -o Makefile albatross-display.pro

dist: 
	@mkdir -p .tmp/albatross-display && $(COPY_FILE) --parents $(SOURCES) $(HEADERS) $(FORMS) $(DIST) .tmp/albatross-display/ && $(COPY_FILE) --parents Ades.ui.h ArcTyp.ui.h Assr.ui.h Brightness.ui.h ChangePassword.ui.h CustomSetDialog.ui.h FindTrackDlg.ui.h FlSelect.ui.h FlSelectOther.ui.h HeightFilterDlg.ui.h Runway.ui.h SaveAs.ui.h SignIn.ui.h SystemInfo.ui.h TrackControl.ui.h Tssr.ui.h TssrOther.ui.h Wtc.ui.h .tmp/albatross-display/ && ( cd `dirname .tmp/albatross-display` && $(TAR) albatross-display.tar albatross-display && $(GZIP) albatross-display.tar ) && $(MOVE) `dirname .tmp/albatross-display`/albatross-display.tar.gz . && $(DEL_FILE) -r .tmp/albatross-display

mocclean:
	-$(DEL_FILE) $(OBJMOC)
	-$(DEL_FILE) $(SRCMOC)

uiclean:
	-$(DEL_FILE) $(UICIMPLS) $(UICDECLS)

yaccclean:
lexclean:
clean: mocclean uiclean
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) $(TARGET)


FORCE:

####### Compile

AsdApp.o: AsdApp.cpp StdAfx.h \
		AsdApp.h \
		WdwMngr.h \
		FontMngr.h \
		DataMngr.h \
		ColorMngr.h \
		View.h \
		DisplayElement.h \
		AsdView.h \
		AsdMenu.h \
		TrackControl.h \
		RwdView.h \
		Track.h \
		FlightPlan.h \
		InfoMngr.h \
		CouplingMngr.h \
		SetupMngr.h \
		Elements.h \
		Geo.h \
		VisuMap.h \
		Zooming.xpm \
		NormalSelect.xpm \
		Crosshair.xpm \
		UserMngr.h \
		WinHints.h \
		SystemMode.h \
		Interface.h \
		WfAttrib.h \
		SafetyEventHandler.h \
		LineView.h \
		SKMessageBox.h \
		CommonFiles/CommonObject.h \
		CommonFiles/CommonMenu.h \
		CommonFiles/Templ.h \
		CommonDataTypes.h \
		TopLevel.h \
		TimeWnd.h \
		Brightness.h \
		SystemInfo.h \
		SaveAs.h \
		CustomSetDialog.h \
		FindTrackDlg.h \
		CommonFiles/IniFile.h \
		VisuSocket.h \
		String.h \
		AsyncSocket.h \
		HeightFilterDlg.h \
		StatusBar.h \
		CommonFiles/GraphicSymbol.h \
		TrackList.h \
		Wtc.h \
		Tssr.h \
		FlSelectOther.h \
		FlSelect.h \
		TssrOther.h \
		ArcTyp.h \
		Ades.h \
		Assr.h \
		Runway.h \
		SignIn.h \
		ChangePassword.h

AsdMenu.o: AsdMenu.cpp StdAfx.h \
		AsdMenu.h \
		ColorMngr.h \
		FontMngr.h \
		WdwMngr.h \
		AsdApp.h \
		SKMessageBox.h \
		CommonFiles/CommonObject.h \
		CommonFiles/CommonMenu.h \
		CommonFiles/Templ.h \
		WfAttrib.h \
		CommonDataTypes.h \
		TopLevel.h \
		TimeWnd.h \
		Interface.h \
		Brightness.h \
		SystemInfo.h \
		SaveAs.h \
		CustomSetDialog.h \
		FindTrackDlg.h \
		CommonFiles/IniFile.h \
		SetupMngr.h \
		VisuSocket.h \
		String.h \
		AsyncSocket.h

AsdView.o: AsdView.cpp StdAfx.h \
		View.h \
		AsdView.h \
		Elements.h \
		ColorMngr.h \
		SKMessageBox.h \
		CommonFiles/CommonObject.h \
		CommonFiles/CommonMenu.h \
		CommonFiles/Templ.h \
		WdwMngr.h \
		DisplayElement.h \
		CommonFiles/GraphicSymbol.h \
		Interface.h \
		VisuSocket.h \
		String.h \
		AsyncSocket.h

Asterix.o: Asterix.cpp StdAfx.h \
		Asterix.h \
		SKMessageBox.h \
		CommonFiles/CommonObject.h \
		CommonFiles/CommonMenu.h \
		CommonFiles/Templ.h \
		WdwMngr.h \
		String.h

AsyncSocket.o: AsyncSocket.cpp StdAfx.h \
		AsyncSocket.h \
		SKMessageBox.h \
		CommonFiles/CommonObject.h \
		CommonFiles/CommonMenu.h \
		CommonFiles/Templ.h \
		WdwMngr.h

ClientSocket.o: ClientSocket.cpp StdAfx.h \
		AsyncSocket.h \
		View.h \
		ClientSocket.h \
		FlightPlan.h \
		AsdApp.h \
		AsdMenu.h \
		SKMessageBox.h \
		CommonFiles/CommonObject.h \
		CommonFiles/CommonMenu.h \
		CommonFiles/Templ.h \
		WdwMngr.h \
		CommonDataTypes.h \
		Geo.h \
		DisplayElement.h \
		LineView.h \
		AsdView.h \
		WfAttrib.h \
		TopLevel.h \
		TimeWnd.h \
		Interface.h \
		Brightness.h \
		SystemInfo.h \
		SaveAs.h \
		CustomSetDialog.h \
		FindTrackDlg.h \
		ColorMngr.h \
		CommonFiles/IniFile.h \
		SetupMngr.h \
		VisuSocket.h \
		String.h

ColorMngr.o: ColorMngr.cpp StdAfx.h \
		ColorMngr.h \
		CommonFiles/IniFile.h \
		AsdApp.h \
		View.h \
		DisplayElement.h \
		VisuMap.h \
		RwdView.h \
		SKMessageBox.h \
		CommonFiles/CommonObject.h \
		CommonFiles/CommonMenu.h \
		CommonFiles/Templ.h \
		WdwMngr.h \
		WfAttrib.h \
		CommonDataTypes.h \
		TopLevel.h \
		TimeWnd.h \
		Interface.h \
		AsdMenu.h \
		Brightness.h \
		SystemInfo.h \
		SaveAs.h \
		CustomSetDialog.h \
		FindTrackDlg.h \
		SetupMngr.h \
		VisuSocket.h \
		String.h \
		AsyncSocket.h \
		AsdView.h \
		CommonFiles/GraphicSymbol.h \
		TrackControl.h \
		HeightFilterDlg.h \
		StatusBar.h

CommonDataTypes.o: CommonDataTypes.cpp CommonDataTypes.h \
		StdAfx.h \
		SKMessageBox.h \
		CommonFiles/CommonObject.h \
		CommonFiles/CommonMenu.h \
		CommonFiles/Templ.h \
		WdwMngr.h

CouplingMngr.o: CouplingMngr.cpp StdAfx.h \
		View.h \
		AsdView.h \
		CouplingMngr.h \
		AsdApp.h \
		Track.h \
		SKMessageBox.h \
		CommonFiles/CommonObject.h \
		CommonFiles/CommonMenu.h \
		CommonFiles/Templ.h \
		WdwMngr.h \
		CommonDataTypes.h \
		TrackList.h \
		WfAttrib.h \
		TopLevel.h \
		TimeWnd.h \
		Interface.h \
		AsdMenu.h \
		Brightness.h \
		SystemInfo.h \
		SaveAs.h \
		CustomSetDialog.h \
		FindTrackDlg.h \
		ColorMngr.h \
		CommonFiles/IniFile.h \
		SetupMngr.h \
		VisuSocket.h \
		String.h \
		AsyncSocket.h \
		DisplayElement.h \
		CommonFiles/GraphicSymbol.h \
		RwdView.h \
		Wtc.h \
		Tssr.h \
		FlSelectOther.h \
		FlSelect.h \
		TssrOther.h \
		ArcTyp.h \
		Ades.h \
		Assr.h \
		Runway.h \
		Elements.h \
		TrackControl.h \
		HeightFilterDlg.h \
		StatusBar.h \
		DataMngr.h

DataMngr.o: DataMngr.cpp StdAfx.h \
		DataMngr.h \
		ColorMngr.h \
		CommonFiles/IniFile.h \
		String.h \
		AsdApp.h \
		WinHints.h \
		SKMessageBox.h \
		CommonFiles/CommonObject.h \
		CommonFiles/CommonMenu.h \
		CommonFiles/Templ.h \
		WdwMngr.h \
		WfAttrib.h \
		CommonDataTypes.h \
		TopLevel.h \
		TimeWnd.h \
		Interface.h \
		AsdMenu.h \
		Brightness.h \
		SystemInfo.h \
		SaveAs.h \
		CustomSetDialog.h \
		FindTrackDlg.h \
		SetupMngr.h \
		VisuSocket.h \
		AsyncSocket.h

Elements.o: Elements.cpp StdAfx.h \
		View.h \
		AsdView.h \
		Elements.h \
		RwdView.h \
		Track.h \
		ColorMngr.h \
		FontMngr.h \
		WdwMngr.h \
		CommonFiles/IniFile.h \
		Asterix.h \
		AsdApp.h \
		TopLevel.h \
		Geo.h \
		InfoMngr.h \
		SKMessageBox.h \
		CommonFiles/CommonObject.h \
		CommonFiles/CommonMenu.h \
		CommonFiles/Templ.h \
		DisplayElement.h \
		CommonFiles/GraphicSymbol.h \
		Interface.h \
		VisuSocket.h \
		String.h \
		AsyncSocket.h \
		AsdMenu.h \
		TrackControl.h \
		HeightFilterDlg.h \
		StatusBar.h \
		TrackList.h \
		CommonDataTypes.h \
		Wtc.h \
		Tssr.h \
		FlSelectOther.h \
		FlSelect.h \
		TssrOther.h \
		ArcTyp.h \
		Ades.h \
		Assr.h \
		Runway.h \
		WfAttrib.h \
		TimeWnd.h \
		Brightness.h \
		SystemInfo.h \
		SaveAs.h \
		CustomSetDialog.h \
		FindTrackDlg.h \
		SetupMngr.h \
		DataMngr.h

FlightPlan.o: FlightPlan.cpp StdAfx.h \
		FlightPlan.h \
		Geo.h \
		AsdApp.h \
		View.h \
		DisplayElement.h \
		LineView.h \
		FontMngr.h \
		ColorMngr.h \
		Track.h \
		InfoMngr.h \
		CouplingMngr.h \
		SKMessageBox.h \
		CommonFiles/CommonObject.h \
		CommonFiles/CommonMenu.h \
		CommonFiles/Templ.h \
		WdwMngr.h \
		CommonDataTypes.h \
		AsdView.h \
		WfAttrib.h \
		TopLevel.h \
		TimeWnd.h \
		Interface.h \
		AsdMenu.h \
		Brightness.h \
		SystemInfo.h \
		SaveAs.h \
		CustomSetDialog.h \
		FindTrackDlg.h \
		CommonFiles/IniFile.h \
		SetupMngr.h \
		VisuSocket.h \
		String.h \
		AsyncSocket.h \
		CommonFiles/GraphicSymbol.h \
		TrackList.h \
		RwdView.h \
		Wtc.h \
		Tssr.h \
		FlSelectOther.h \
		FlSelect.h \
		TssrOther.h \
		ArcTyp.h \
		Ades.h \
		Assr.h \
		Runway.h \
		Elements.h \
		TrackControl.h \
		HeightFilterDlg.h \
		StatusBar.h \
		DataMngr.h

FontMngr.o: FontMngr.cpp StdAfx.h \
		FontMngr.h \
		CommonFiles/IniFile.h \
		AsdApp.h \
		SKMessageBox.h \
		CommonFiles/CommonObject.h \
		CommonFiles/CommonMenu.h \
		CommonFiles/Templ.h \
		WdwMngr.h \
		WfAttrib.h \
		CommonDataTypes.h \
		TopLevel.h \
		TimeWnd.h \
		Interface.h \
		AsdMenu.h \
		Brightness.h \
		SystemInfo.h \
		SaveAs.h \
		CustomSetDialog.h \
		FindTrackDlg.h \
		ColorMngr.h \
		SetupMngr.h \
		VisuSocket.h \
		String.h \
		AsyncSocket.h

Geo.o: Geo.cpp StdAfx.h \
		Geo.h \
		String.h \
		CommonFiles/IniFile.h \
		AsdApp.h \
		SKMessageBox.h \
		CommonFiles/CommonObject.h \
		CommonFiles/CommonMenu.h \
		CommonFiles/Templ.h \
		WdwMngr.h \
		WfAttrib.h \
		CommonDataTypes.h \
		TopLevel.h \
		TimeWnd.h \
		Interface.h \
		AsdMenu.h \
		Brightness.h \
		SystemInfo.h \
		SaveAs.h \
		CustomSetDialog.h \
		FindTrackDlg.h \
		ColorMngr.h \
		SetupMngr.h \
		VisuSocket.h \
		AsyncSocket.h

ImportantTrack.o: ImportantTrack.cpp ImportantTrack.h \
		WinHints.h \
		View.h \
		DisplayElement.h \
		RwdView.h \
		AsdApp.h \
		CommonFiles/IniFile.h \
		WfAttrib.h \
		CommonDataTypes.h \
		TopLevel.h \
		TimeWnd.h \
		Interface.h \
		StdAfx.h \
		AsdMenu.h \
		SKMessageBox.h \
		CommonFiles/CommonObject.h \
		CommonFiles/CommonMenu.h \
		CommonFiles/Templ.h \
		WdwMngr.h \
		Brightness.h \
		SystemInfo.h \
		SaveAs.h \
		CustomSetDialog.h \
		FindTrackDlg.h \
		ColorMngr.h \
		SetupMngr.h \
		VisuSocket.h \
		String.h \
		AsyncSocket.h \
		AsdView.h \
		TrackControl.h \
		HeightFilterDlg.h \
		StatusBar.h

InfoMngr.o: InfoMngr.cpp StdAfx.h \
		String.h \
		InfoMngr.h \
		CommonFiles/IniFile.h \
		AsdApp.h \
		SetupMngr.h \
		TopLevel.h \
		UserMngr.h \
		View.h \
		Track.h \
		CommonFiles/HWFile.h \
		SKMessageBox.h \
		CommonFiles/CommonObject.h \
		CommonFiles/CommonMenu.h \
		CommonFiles/Templ.h \
		WdwMngr.h \
		CommonDataTypes.h \
		WfAttrib.h \
		TimeWnd.h \
		Interface.h \
		AsdMenu.h \
		Brightness.h \
		SystemInfo.h \
		SaveAs.h \
		CustomSetDialog.h \
		FindTrackDlg.h \
		ColorMngr.h \
		VisuSocket.h \
		AsyncSocket.h \
		SignIn.h \
		ChangePassword.h \
		DisplayElement.h \
		CommonFiles/GraphicSymbol.h \
		TrackList.h \
		RwdView.h \
		Wtc.h \
		Tssr.h \
		FlSelectOther.h \
		FlSelect.h \
		TssrOther.h \
		ArcTyp.h \
		Ades.h \
		Assr.h \
		Runway.h \
		Elements.h \
		AsdView.h \
		TrackControl.h \
		HeightFilterDlg.h \
		StatusBar.h \
		DataMngr.h

Interface.o: Interface.cpp StdAfx.h \
		CommonFiles/IniFile.h \
		Interface.h \
		SKMessageBox.h \
		CommonFiles/CommonObject.h \
		CommonFiles/CommonMenu.h \
		CommonFiles/Templ.h \
		WdwMngr.h \
		VisuSocket.h \
		String.h \
		AsyncSocket.h

LineView.o: LineView.cpp StdAfx.h \
		View.h \
		DisplayElement.h \
		LineView.h \
		ColorMngr.h \
		FontMngr.h \
		SKMessageBox.h \
		CommonFiles/CommonObject.h \
		CommonFiles/CommonMenu.h \
		CommonFiles/Templ.h \
		WdwMngr.h \
		AsdView.h

Main.o: Main.cpp StdAfx.h \
		AsdApp.h \
		WdwMngr.h \
		SKMessageBox.h \
		CommonFiles/CommonObject.h \
		CommonFiles/CommonMenu.h \
		CommonFiles/Templ.h \
		WfAttrib.h \
		CommonDataTypes.h \
		TopLevel.h \
		TimeWnd.h \
		Interface.h \
		AsdMenu.h \
		Brightness.h \
		SystemInfo.h \
		SaveAs.h \
		CustomSetDialog.h \
		FindTrackDlg.h \
		ColorMngr.h \
		CommonFiles/IniFile.h \
		SetupMngr.h \
		VisuSocket.h \
		String.h \
		AsyncSocket.h

RwdView.o: RwdView.cpp StdAfx.h \
		View.h \
		DisplayElement.h \
		VisuMap.h \
		RwdView.h \
		Track.h \
		AsdMenu.h \
		Elements.h \
		Geo.h \
		FontMngr.h \
		ColorMngr.h \
		WdwMngr.h \
		SetupMngr.h \
		CommonFiles/IniFile.h \
		AsdApp.h \
		String.h \
		DataMngr.h \
		WinHints.h \
		SKMessageBox.h \
		TopLevel.h \
		InfoMngr.h \
		ImportantTrack.h \
		LineView.h \
		CommonFiles/CommonObject.h \
		CommonFiles/CommonMenu.h \
		CommonFiles/Templ.h \
		AsdView.h \
		CommonFiles/GraphicSymbol.h \
		TrackControl.h \
		HeightFilterDlg.h \
		StatusBar.h \
		TrackList.h \
		CommonDataTypes.h \
		Wtc.h \
		Tssr.h \
		FlSelectOther.h \
		FlSelect.h \
		TssrOther.h \
		ArcTyp.h \
		Ades.h \
		Assr.h \
		Runway.h \
		WfAttrib.h \
		TimeWnd.h \
		Interface.h \
		Brightness.h \
		SystemInfo.h \
		SaveAs.h \
		CustomSetDialog.h \
		FindTrackDlg.h \
		VisuSocket.h \
		AsyncSocket.h

SafetyEventHandler.o: SafetyEventHandler.cpp StdAfx.h \
		View.h \
		AsdView.h \
		DisplayElement.h \
		CommonFiles/GraphicSymbol.h \
		Track.h \
		AsdApp.h \
		VisuMap.h \
		SafetyEventHandler.h \
		CouplingMngr.h \
		FlightPlan.h \
		TopLevel.h \
		DataMngr.h \
		Elements.h \
		UserMngr.h \
		WinHints.h \
		LineView.h \
		SKMessageBox.h \
		CommonFiles/CommonObject.h \
		CommonFiles/CommonMenu.h \
		CommonFiles/Templ.h \
		WdwMngr.h \
		TrackList.h \
		CommonDataTypes.h \
		RwdView.h \
		Wtc.h \
		Tssr.h \
		FlSelectOther.h \
		FlSelect.h \
		TssrOther.h \
		ArcTyp.h \
		Ades.h \
		Assr.h \
		Runway.h \
		WfAttrib.h \
		TimeWnd.h \
		Interface.h \
		AsdMenu.h \
		Brightness.h \
		SystemInfo.h \
		SaveAs.h \
		CustomSetDialog.h \
		FindTrackDlg.h \
		ColorMngr.h \
		CommonFiles/IniFile.h \
		SetupMngr.h \
		VisuSocket.h \
		String.h \
		AsyncSocket.h \
		TrackControl.h \
		HeightFilterDlg.h \
		StatusBar.h \
		SystemMode.h \
		InfoMngr.h \
		Geo.h \
		SignIn.h \
		ChangePassword.h

SetupMngr.o: SetupMngr.cpp StdAfx.h \
		AsdApp.h \
		SetupMngr.h \
		ColorMngr.h \
		CommonFiles/IniFile.h \
		SKMessageBox.h \
		CommonFiles/CommonObject.h \
		CommonFiles/CommonMenu.h \
		CommonFiles/Templ.h \
		WdwMngr.h \
		WfAttrib.h \
		CommonDataTypes.h \
		TopLevel.h \
		TimeWnd.h \
		Interface.h \
		AsdMenu.h \
		Brightness.h \
		SystemInfo.h \
		SaveAs.h \
		CustomSetDialog.h \
		FindTrackDlg.h \
		VisuSocket.h \
		String.h \
		AsyncSocket.h

SKMessageBox.o: SKMessageBox.cpp SKMessageBox.h \
		WinHints.h \
		AsdApp.h \
		WdwMngr.h \
		WfAttrib.h \
		CommonDataTypes.h \
		TopLevel.h \
		TimeWnd.h \
		Interface.h \
		StdAfx.h \
		AsdMenu.h \
		CommonFiles/CommonObject.h \
		CommonFiles/CommonMenu.h \
		CommonFiles/Templ.h \
		Brightness.h \
		SystemInfo.h \
		SaveAs.h \
		CustomSetDialog.h \
		FindTrackDlg.h \
		ColorMngr.h \
		CommonFiles/IniFile.h \
		SetupMngr.h \
		VisuSocket.h \
		String.h \
		AsyncSocket.h

StatusBar.o: StatusBar.cpp StdAfx.h \
		StatusBar.h \
		View.h \
		DisplayElement.h \
		VisuMap.h \
		RwdView.h \
		ColorMngr.h \
		FontMngr.h \
		SKMessageBox.h \
		CommonFiles/CommonObject.h \
		CommonFiles/CommonMenu.h \
		CommonFiles/Templ.h \
		WdwMngr.h \
		AsdView.h \
		AsdMenu.h \
		CommonFiles/GraphicSymbol.h \
		TrackControl.h \
		HeightFilterDlg.h

String.o: String.cpp StdAfx.h \
		String.h \
		SKMessageBox.h \
		CommonFiles/CommonObject.h \
		CommonFiles/CommonMenu.h \
		CommonFiles/Templ.h \
		WdwMngr.h

SystemMode.o: SystemMode.cpp StdAfx.h \
		SystemMode.h \
		View.h \
		DisplayElement.h \
		RwdView.h \
		AsdApp.h \
		Track.h \
		InfoMngr.h \
		CouplingMngr.h \
		FlightPlan.h \
		TopLevel.h \
		VisuMap.h \
		SKMessageBox.h \
		CommonFiles/CommonObject.h \
		CommonFiles/CommonMenu.h \
		CommonFiles/Templ.h \
		WdwMngr.h \
		CommonDataTypes.h \
		AsdView.h \
		AsdMenu.h \
		TrackControl.h \
		HeightFilterDlg.h \
		StatusBar.h \
		WfAttrib.h \
		TimeWnd.h \
		Interface.h \
		Brightness.h \
		SystemInfo.h \
		SaveAs.h \
		CustomSetDialog.h \
		FindTrackDlg.h \
		ColorMngr.h \
		CommonFiles/IniFile.h \
		SetupMngr.h \
		VisuSocket.h \
		String.h \
		AsyncSocket.h \
		CommonFiles/GraphicSymbol.h \
		TrackList.h \
		Wtc.h \
		Tssr.h \
		FlSelectOther.h \
		FlSelect.h \
		TssrOther.h \
		ArcTyp.h \
		Ades.h \
		Assr.h \
		Runway.h \
		Elements.h \
		DataMngr.h \
		Geo.h \
		LineView.h

TimeWnd.o: TimeWnd.cpp StdAfx.h \
		TimeWnd.h \
		AsdApp.h \
		ColorMngr.h \
		FontMngr.h \
		WdwMngr.h \
		InfoMngr.h \
		SKMessageBox.h \
		CommonFiles/CommonObject.h \
		CommonFiles/CommonMenu.h \
		CommonFiles/Templ.h \
		WfAttrib.h \
		CommonDataTypes.h \
		TopLevel.h \
		Interface.h \
		AsdMenu.h \
		Brightness.h \
		SystemInfo.h \
		SaveAs.h \
		CustomSetDialog.h \
		FindTrackDlg.h \
		CommonFiles/IniFile.h \
		SetupMngr.h \
		VisuSocket.h \
		String.h \
		AsyncSocket.h

TopLevel.o: TopLevel.cpp StdAfx.h \
		AsdApp.h \
		AsdMenu.h \
		TopLevel.h \
		FontMngr.h \
		ColorMngr.h \
		WdwMngr.h \
		View.h \
		AsdView.h \
		DisplayElement.h \
		VisuMap.h \
		RwdView.h \
		Elements.h \
		Track.h \
		SetupMngr.h \
		CommonFiles/IniFile.h \
		WinHints.h \
		UserMngr.h \
		TimeWnd.h \
		InfoMngr.h \
		SystemMode.h \
		FlightPlan.h \
		SKMessageBox.h \
		CommonFiles/CommonObject.h \
		CommonFiles/CommonMenu.h \
		CommonFiles/Templ.h \
		WfAttrib.h \
		CommonDataTypes.h \
		Interface.h \
		Brightness.h \
		SystemInfo.h \
		SaveAs.h \
		CustomSetDialog.h \
		FindTrackDlg.h \
		VisuSocket.h \
		String.h \
		AsyncSocket.h \
		CommonFiles/GraphicSymbol.h \
		TrackControl.h \
		HeightFilterDlg.h \
		StatusBar.h \
		TrackList.h \
		Wtc.h \
		Tssr.h \
		FlSelectOther.h \
		FlSelect.h \
		TssrOther.h \
		ArcTyp.h \
		Ades.h \
		Assr.h \
		Runway.h \
		DataMngr.h \
		SignIn.h \
		ChangePassword.h \
		Geo.h \
		LineView.h

Track.o: Track.cpp StdAfx.h \
		View.h \
		AsdView.h \
		DisplayElement.h \
		Track.h \
		RwdView.h \
		Elements.h \
		ColorMngr.h \
		FontMngr.h \
		DataMngr.h \
		CommonFiles/IniFile.h \
		Geo.h \
		FlSelectOther.h \
		AsdApp.h \
		Asterix.h \
		InfoMngr.h \
		UserMngr.h \
		FlSelect.h \
		Tssr.h \
		TssrOther.h \
		TopLevel.h \
		WfAttrib.h \
		WdwMngr.h \
		Interface.h \
		Wtc.h \
		ArcTyp.h \
		SKMessageBox.h \
		Ades.h \
		Assr.h \
		VisuMap.h \
		CommonDataTypes.h \
		LineView.h \
		FlightPlan.h \
		CouplingMngr.h \
		CommonFiles/CommonObject.h \
		CommonFiles/CommonMenu.h \
		CommonFiles/Templ.h \
		CommonFiles/GraphicSymbol.h \
		TrackList.h \
		Runway.h \
		TimeWnd.h \
		AsdMenu.h \
		Brightness.h \
		SystemInfo.h \
		SaveAs.h \
		CustomSetDialog.h \
		FindTrackDlg.h \
		SetupMngr.h \
		VisuSocket.h \
		String.h \
		AsyncSocket.h \
		TrackControl.h \
		HeightFilterDlg.h \
		StatusBar.h \
		SignIn.h \
		ChangePassword.h

TrackList.o: TrackList.cpp StdAfx.h \
		TrackList.h \
		SKMessageBox.h \
		CommonFiles/CommonObject.h \
		CommonFiles/CommonMenu.h \
		CommonFiles/Templ.h \
		WdwMngr.h \
		CommonDataTypes.h

UserMngr.o: UserMngr.cpp UserMngr.h \
		AsdApp.h \
		WdwMngr.h \
		TopLevel.h \
		WinHints.h \
		SKMessageBox.h \
		InfoMngr.h \
		StdAfx.h \
		SignIn.h \
		ChangePassword.h \
		CommonFiles/IniFile.h \
		CommonFiles/CommonObject.h \
		CommonFiles/CommonMenu.h \
		CommonFiles/Templ.h \
		WfAttrib.h \
		CommonDataTypes.h \
		TimeWnd.h \
		Interface.h \
		AsdMenu.h \
		Brightness.h \
		SystemInfo.h \
		SaveAs.h \
		CustomSetDialog.h \
		FindTrackDlg.h \
		ColorMngr.h \
		SetupMngr.h \
		VisuSocket.h \
		String.h \
		AsyncSocket.h

View.o: View.cpp StdAfx.h \
		View.h \
		SKMessageBox.h \
		CommonFiles/CommonObject.h \
		CommonFiles/CommonMenu.h \
		CommonFiles/Templ.h \
		WdwMngr.h

VisuMap.o: VisuMap.cpp StdAfx.h \
		View.h \
		DisplayElement.h \
		VisuMap.h \
		ColorMngr.h \
		AsdApp.h \
		Track.h \
		SKMessageBox.h \
		CommonFiles/CommonObject.h \
		CommonFiles/CommonMenu.h \
		CommonFiles/Templ.h \
		WdwMngr.h \
		AsdView.h \
		AsdMenu.h \
		RwdView.h \
		CommonFiles/GraphicSymbol.h \
		TrackControl.h \
		HeightFilterDlg.h \
		StatusBar.h \
		WfAttrib.h \
		CommonDataTypes.h \
		TopLevel.h \
		TimeWnd.h \
		Interface.h \
		Brightness.h \
		SystemInfo.h \
		SaveAs.h \
		CustomSetDialog.h \
		FindTrackDlg.h \
		CommonFiles/IniFile.h \
		SetupMngr.h \
		VisuSocket.h \
		String.h \
		AsyncSocket.h \
		TrackList.h \
		Wtc.h \
		Tssr.h \
		FlSelectOther.h \
		FlSelect.h \
		TssrOther.h \
		ArcTyp.h \
		Ades.h \
		Assr.h \
		Runway.h \
		Elements.h \
		DataMngr.h

VisuSocket.o: VisuSocket.cpp StdAfx.h \
		AsyncSocket.h \
		VisuSocket.h \
		AsdApp.h \
		SKMessageBox.h \
		CommonFiles/CommonObject.h \
		CommonFiles/CommonMenu.h \
		CommonFiles/Templ.h \
		WdwMngr.h \
		WfAttrib.h \
		CommonDataTypes.h \
		TopLevel.h \
		TimeWnd.h \
		Interface.h \
		AsdMenu.h \
		Brightness.h \
		SystemInfo.h \
		SaveAs.h \
		CustomSetDialog.h \
		FindTrackDlg.h \
		ColorMngr.h \
		CommonFiles/IniFile.h \
		SetupMngr.h \
		String.h

WdwMngr.o: WdwMngr.cpp StdAfx.h \
		WdwMngr.h \
		CommonFiles/IniFile.h \
		AsdApp.h \
		WinHints.h \
		WfAttrib.h \
		ImportantTrack.h \
		SKMessageBox.h \
		CommonFiles/CommonObject.h \
		CommonFiles/CommonMenu.h \
		CommonFiles/Templ.h \
		CommonDataTypes.h \
		TopLevel.h \
		TimeWnd.h \
		Interface.h \
		AsdMenu.h \
		Brightness.h \
		SystemInfo.h \
		SaveAs.h \
		CustomSetDialog.h \
		FindTrackDlg.h \
		ColorMngr.h \
		SetupMngr.h \
		VisuSocket.h \
		String.h \
		AsyncSocket.h

WfAttrib.o: WfAttrib.cpp WfAttrib.h \
		WinHints.h \
		CommonFiles/IniFile.h \
		AsdApp.h \
		SKMessageBox.h \
		DataMngr.h \
		StdAfx.h \
		AsdMenu.h \
		CommonFiles/CommonObject.h \
		CommonFiles/CommonMenu.h \
		CommonFiles/Templ.h \
		WdwMngr.h \
		CommonDataTypes.h \
		TopLevel.h \
		TimeWnd.h \
		Interface.h \
		Brightness.h \
		SystemInfo.h \
		SaveAs.h \
		CustomSetDialog.h \
		FindTrackDlg.h \
		ColorMngr.h \
		SetupMngr.h \
		VisuSocket.h \
		String.h \
		AsyncSocket.h

WinHints.o: WinHints.cpp WinHints.h \
		SKMessageBox.h \
		ColorMngr.h \
		WdwMngr.h

CDirectoryFileOperations.o: CommonFiles/CDirectoryFileOperations.cpp CommonFiles/CDirectoryFileOperations.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CDirectoryFileOperations.o CommonFiles/CDirectoryFileOperations.cpp

CommonMenu.o: CommonFiles/CommonMenu.cpp CommonFiles/Templ.h \
		CommonFiles/CommonObject.h \
		CommonFiles/CommonMenu.h \
		AsdMenu.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CommonMenu.o CommonFiles/CommonMenu.cpp

CommonObject.o: CommonFiles/CommonObject.cpp CommonFiles/CommonObject.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CommonObject.o CommonFiles/CommonObject.cpp

Files.o: CommonFiles/Files.cpp StdAfx.h \
		CommonFiles/Files.h \
		SKMessageBox.h \
		CommonFiles/CommonObject.h \
		CommonFiles/CommonMenu.h \
		CommonFiles/Templ.h \
		WdwMngr.h \
		CommonFiles/IniFile.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Files.o CommonFiles/Files.cpp

GraphicSymbol.o: CommonFiles/GraphicSymbol.cpp CommonFiles/Templ.h \
		CommonFiles/CommonObject.h \
		CommonFiles/CommonMenu.h \
		CommonFiles/GraphicSymbol.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o GraphicSymbol.o CommonFiles/GraphicSymbol.cpp

HWFile.o: CommonFiles/HWFile.cpp CommonFiles/Templ.h \
		CommonFiles/HWFile.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o HWFile.o CommonFiles/HWFile.cpp

IniFile.o: CommonFiles/IniFile.cpp CommonFiles/Templ.h \
		CommonFiles/IniFile.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o IniFile.o CommonFiles/IniFile.cpp

IPAddressValidator.o: CommonFiles/IPAddressValidator.cpp CommonFiles/IPAddressValidator.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o IPAddressValidator.o CommonFiles/IPAddressValidator.cpp

VersionNumberValidator.o: CommonFiles/VersionNumberValidator.cpp CommonFiles/VersionNumberValidator.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o VersionNumberValidator.o CommonFiles/VersionNumberValidator.cpp

Ades.h: Ades.ui StdAfx.h \
		DataMngr.h \
		SKMessageBox.h \
		CommonFiles/CommonObject.h \
		CommonFiles/CommonMenu.h \
		CommonFiles/Templ.h \
		WdwMngr.h
	$(UIC) Ades.ui -o Ades.h

Ades.cpp: Ades.h Ades.ui Ades.ui.h StdAfx.h \
		DataMngr.h \
		SKMessageBox.h \
		CommonFiles/CommonObject.h \
		CommonFiles/CommonMenu.h \
		CommonFiles/Templ.h \
		WdwMngr.h
	$(UIC) Ades.ui -i Ades.h -o Ades.cpp

ArcTyp.h: ArcTyp.ui StdAfx.h \
		DataMngr.h \
		SKMessageBox.h \
		CommonFiles/CommonObject.h \
		CommonFiles/CommonMenu.h \
		CommonFiles/Templ.h \
		WdwMngr.h
	$(UIC) ArcTyp.ui -o ArcTyp.h

ArcTyp.cpp: ArcTyp.h ArcTyp.ui ArcTyp.ui.h StdAfx.h \
		DataMngr.h \
		SKMessageBox.h \
		CommonFiles/CommonObject.h \
		CommonFiles/CommonMenu.h \
		CommonFiles/Templ.h \
		WdwMngr.h
	$(UIC) ArcTyp.ui -i ArcTyp.h -o ArcTyp.cpp

Assr.h: Assr.ui 
	$(UIC) Assr.ui -o Assr.h

Assr.cpp: Assr.h Assr.ui Assr.ui.h 
	$(UIC) Assr.ui -i Assr.h -o Assr.cpp

Brightness.h: Brightness.ui 
	$(UIC) Brightness.ui -o Brightness.h

Brightness.cpp: Brightness.h Brightness.ui Brightness.ui.h 
	$(UIC) Brightness.ui -i Brightness.h -o Brightness.cpp

ChangePassword.h: ChangePassword.ui AsdApp.h \
		WfAttrib.h \
		CommonDataTypes.h \
		TopLevel.h \
		TimeWnd.h \
		Interface.h \
		StdAfx.h \
		AsdMenu.h \
		SKMessageBox.h \
		CommonFiles/CommonObject.h \
		CommonFiles/CommonMenu.h \
		CommonFiles/Templ.h \
		WdwMngr.h \
		Brightness.h \
		SystemInfo.h \
		SaveAs.h \
		CustomSetDialog.h \
		FindTrackDlg.h \
		ColorMngr.h \
		CommonFiles/IniFile.h \
		SetupMngr.h \
		VisuSocket.h \
		String.h \
		AsyncSocket.h
	$(UIC) ChangePassword.ui -o ChangePassword.h

ChangePassword.cpp: ChangePassword.h ChangePassword.ui ChangePassword.ui.h AsdApp.h \
		WfAttrib.h \
		CommonDataTypes.h \
		TopLevel.h \
		TimeWnd.h \
		Interface.h \
		StdAfx.h \
		AsdMenu.h \
		SKMessageBox.h \
		CommonFiles/CommonObject.h \
		CommonFiles/CommonMenu.h \
		CommonFiles/Templ.h \
		WdwMngr.h \
		Brightness.h \
		SystemInfo.h \
		SaveAs.h \
		CustomSetDialog.h \
		FindTrackDlg.h \
		ColorMngr.h \
		CommonFiles/IniFile.h \
		SetupMngr.h \
		VisuSocket.h \
		String.h \
		AsyncSocket.h
	$(UIC) ChangePassword.ui -i ChangePassword.h -o ChangePassword.cpp

CustomSetDialog.h: CustomSetDialog.ui ColorMngr.h \
		CommonFiles/IniFile.h \
		StdAfx.h \
		SetupMngr.h \
		CommonFiles/Templ.h \
		SKMessageBox.h \
		CommonFiles/CommonObject.h \
		CommonFiles/CommonMenu.h \
		WdwMngr.h
	$(UIC) CustomSetDialog.ui -o CustomSetDialog.h

CustomSetDialog.cpp: CustomSetDialog.h CustomSetDialog.ui CustomSetDialog.ui.h ColorMngr.h \
		CommonFiles/IniFile.h \
		StdAfx.h \
		SetupMngr.h \
		CommonFiles/Templ.h \
		SKMessageBox.h \
		CommonFiles/CommonObject.h \
		CommonFiles/CommonMenu.h \
		WdwMngr.h
	$(UIC) CustomSetDialog.ui -i CustomSetDialog.h -o CustomSetDialog.cpp

FindTrackDlg.h: FindTrackDlg.ui StdAfx.h \
		SKMessageBox.h \
		CommonFiles/CommonObject.h \
		CommonFiles/CommonMenu.h \
		CommonFiles/Templ.h \
		WdwMngr.h
	$(UIC) FindTrackDlg.ui -o FindTrackDlg.h

FindTrackDlg.cpp: FindTrackDlg.h FindTrackDlg.ui FindTrackDlg.ui.h StdAfx.h \
		SKMessageBox.h \
		CommonFiles/CommonObject.h \
		CommonFiles/CommonMenu.h \
		CommonFiles/Templ.h \
		WdwMngr.h
	$(UIC) FindTrackDlg.ui -i FindTrackDlg.h -o FindTrackDlg.cpp

FlSelect.h: FlSelect.ui 
	$(UIC) FlSelect.ui -o FlSelect.h

FlSelect.cpp: FlSelect.h FlSelect.ui FlSelect.ui.h 
	$(UIC) FlSelect.ui -i FlSelect.h -o FlSelect.cpp

FlSelectOther.h: FlSelectOther.ui 
	$(UIC) FlSelectOther.ui -o FlSelectOther.h

FlSelectOther.cpp: FlSelectOther.h FlSelectOther.ui FlSelectOther.ui.h 
	$(UIC) FlSelectOther.ui -i FlSelectOther.h -o FlSelectOther.cpp

HeightFilterDlg.h: HeightFilterDlg.ui 
	$(UIC) HeightFilterDlg.ui -o HeightFilterDlg.h

HeightFilterDlg.cpp: HeightFilterDlg.h HeightFilterDlg.ui HeightFilterDlg.ui.h 
	$(UIC) HeightFilterDlg.ui -i HeightFilterDlg.h -o HeightFilterDlg.cpp

Runway.h: Runway.ui StdAfx.h \
		SKMessageBox.h \
		CommonFiles/CommonObject.h \
		CommonFiles/CommonMenu.h \
		CommonFiles/Templ.h \
		WdwMngr.h
	$(UIC) Runway.ui -o Runway.h

Runway.cpp: Runway.h Runway.ui Runway.ui.h StdAfx.h \
		SKMessageBox.h \
		CommonFiles/CommonObject.h \
		CommonFiles/CommonMenu.h \
		CommonFiles/Templ.h \
		WdwMngr.h
	$(UIC) Runway.ui -i Runway.h -o Runway.cpp

SaveAs.h: SaveAs.ui 
	$(UIC) SaveAs.ui -o SaveAs.h

SaveAs.cpp: SaveAs.h SaveAs.ui SaveAs.ui.h 
	$(UIC) SaveAs.ui -i SaveAs.h -o SaveAs.cpp

SignIn.h: SignIn.ui 
	$(UIC) SignIn.ui -o SignIn.h

SignIn.cpp: SignIn.h SignIn.ui SignIn.ui.h 
	$(UIC) SignIn.ui -i SignIn.h -o SignIn.cpp

SystemInfo.h: SystemInfo.ui CommonDataTypes.h \
		StdAfx.h \
		SKMessageBox.h \
		CommonFiles/CommonObject.h \
		CommonFiles/CommonMenu.h \
		CommonFiles/Templ.h \
		WdwMngr.h
	$(UIC) SystemInfo.ui -o SystemInfo.h

SystemInfo.cpp: SystemInfo.h SystemInfo.ui SystemInfo.ui.h CommonDataTypes.h \
		StdAfx.h \
		SKMessageBox.h \
		CommonFiles/CommonObject.h \
		CommonFiles/CommonMenu.h \
		CommonFiles/Templ.h \
		WdwMngr.h
	$(UIC) SystemInfo.ui -i SystemInfo.h -o SystemInfo.cpp

TrackControl.h: TrackControl.ui 
	$(UIC) TrackControl.ui -o TrackControl.h

TrackControl.cpp: TrackControl.h TrackControl.ui TrackControl.ui.h 
	$(UIC) TrackControl.ui -i TrackControl.h -o TrackControl.cpp

Tssr.h: Tssr.ui 
	$(UIC) Tssr.ui -o Tssr.h

Tssr.cpp: Tssr.h Tssr.ui Tssr.ui.h 
	$(UIC) Tssr.ui -i Tssr.h -o Tssr.cpp

TssrOther.h: TssrOther.ui 
	$(UIC) TssrOther.ui -o TssrOther.h

TssrOther.cpp: TssrOther.h TssrOther.ui TssrOther.ui.h 
	$(UIC) TssrOther.ui -i TssrOther.h -o TssrOther.cpp

Wtc.h: Wtc.ui StdAfx.h \
		DataMngr.h \
		SKMessageBox.h \
		CommonFiles/CommonObject.h \
		CommonFiles/CommonMenu.h \
		CommonFiles/Templ.h \
		WdwMngr.h
	$(UIC) Wtc.ui -o Wtc.h

Wtc.cpp: Wtc.h Wtc.ui Wtc.ui.h StdAfx.h \
		DataMngr.h \
		SKMessageBox.h \
		CommonFiles/CommonObject.h \
		CommonFiles/CommonMenu.h \
		CommonFiles/Templ.h \
		WdwMngr.h
	$(UIC) Wtc.ui -i Wtc.h -o Wtc.cpp

Ades.o: Ades.cpp Ades.ui.h \
		Ades.h

ArcTyp.o: ArcTyp.cpp ArcTyp.ui.h \
		ArcTyp.h

Assr.o: Assr.cpp Assr.h

Brightness.o: Brightness.cpp Brightness.h

ChangePassword.o: ChangePassword.cpp ChangePassword.ui.h \
		ChangePassword.h

CustomSetDialog.o: CustomSetDialog.cpp SaveAs.h \
		AsdApp.h \
		CustomSetDialog.h

FindTrackDlg.o: FindTrackDlg.cpp FindTrackDlg.ui.h \
		FindTrackDlg.h

FlSelect.o: FlSelect.cpp FlSelect.ui.h \
		FlSelect.h

FlSelectOther.o: FlSelectOther.cpp FlSelectOther.ui.h \
		FlSelectOther.h

HeightFilterDlg.o: HeightFilterDlg.cpp HeightFilterDlg.h

Runway.o: Runway.cpp Runway.h

SaveAs.o: SaveAs.cpp SaveAs.h

SignIn.o: SignIn.cpp SignIn.ui.h \
		SignIn.h

SystemInfo.o: SystemInfo.cpp SystemInfo.ui.h \
		SystemInfo.h

TrackControl.o: TrackControl.cpp TrackControl.ui.h \
		TrackControl.h

Tssr.o: Tssr.cpp Tssr.h

TssrOther.o: TssrOther.cpp TssrOther.h

Wtc.o: Wtc.cpp Wtc.h

moc_AsyncSocket.o: moc_AsyncSocket.cpp  AsyncSocket.h StdAfx.h \
		SKMessageBox.h \
		CommonFiles/CommonObject.h \
		CommonFiles/CommonMenu.h \
		CommonFiles/Templ.h \
		WdwMngr.h

moc_ImportantTrack.o: moc_ImportantTrack.cpp  ImportantTrack.h AsdApp.h \
		WfAttrib.h \
		CommonDataTypes.h \
		TopLevel.h \
		TimeWnd.h \
		Interface.h \
		StdAfx.h \
		AsdMenu.h \
		SKMessageBox.h \
		CommonFiles/CommonObject.h \
		CommonFiles/CommonMenu.h \
		CommonFiles/Templ.h \
		WdwMngr.h \
		Brightness.h \
		SystemInfo.h \
		SaveAs.h \
		CustomSetDialog.h \
		FindTrackDlg.h \
		ColorMngr.h \
		CommonFiles/IniFile.h \
		SetupMngr.h \
		VisuSocket.h \
		String.h \
		AsyncSocket.h

moc_LineView.o: moc_LineView.cpp  LineView.h StdAfx.h \
		View.h \
		DisplayElement.h \
		SKMessageBox.h \
		CommonFiles/CommonObject.h \
		CommonFiles/CommonMenu.h \
		CommonFiles/Templ.h \
		WdwMngr.h \
		AsdView.h

moc_TopLevel.o: moc_TopLevel.cpp  TopLevel.h CommonDataTypes.h \
		Brightness.h \
		StdAfx.h \
		AsdMenu.h \
		SystemInfo.h \
		SaveAs.h \
		CustomSetDialog.h \
		FindTrackDlg.h \
		SKMessageBox.h \
		CommonFiles/CommonObject.h \
		CommonFiles/CommonMenu.h \
		CommonFiles/Templ.h \
		WdwMngr.h \
		ColorMngr.h \
		CommonFiles/IniFile.h \
		SetupMngr.h

moc_View.o: moc_View.cpp  View.h StdAfx.h \
		CommonFiles/CommonObject.h \
		SKMessageBox.h \
		CommonFiles/CommonMenu.h \
		CommonFiles/Templ.h \
		WdwMngr.h

moc_Ades.o: moc_Ades.cpp  Ades.h StdAfx.h \
		DataMngr.h \
		SKMessageBox.h \
		CommonFiles/CommonObject.h \
		CommonFiles/CommonMenu.h \
		CommonFiles/Templ.h \
		WdwMngr.h

moc_ArcTyp.o: moc_ArcTyp.cpp  ArcTyp.h StdAfx.h \
		DataMngr.h \
		SKMessageBox.h \
		CommonFiles/CommonObject.h \
		CommonFiles/CommonMenu.h \
		CommonFiles/Templ.h \
		WdwMngr.h

moc_Assr.o: moc_Assr.cpp  Assr.h 

moc_Brightness.o: moc_Brightness.cpp  Brightness.h 

moc_ChangePassword.o: moc_ChangePassword.cpp  ChangePassword.h AsdApp.h \
		WfAttrib.h \
		CommonDataTypes.h \
		TopLevel.h \
		TimeWnd.h \
		Interface.h \
		StdAfx.h \
		AsdMenu.h \
		SKMessageBox.h \
		CommonFiles/CommonObject.h \
		CommonFiles/CommonMenu.h \
		CommonFiles/Templ.h \
		WdwMngr.h \
		Brightness.h \
		SystemInfo.h \
		SaveAs.h \
		CustomSetDialog.h \
		FindTrackDlg.h \
		ColorMngr.h \
		CommonFiles/IniFile.h \
		SetupMngr.h \
		VisuSocket.h \
		String.h \
		AsyncSocket.h

moc_CustomSetDialog.o: moc_CustomSetDialog.cpp  CustomSetDialog.h ColorMngr.h \
		CommonFiles/IniFile.h \
		StdAfx.h \
		SetupMngr.h \
		CommonFiles/Templ.h \
		SKMessageBox.h \
		CommonFiles/CommonObject.h \
		CommonFiles/CommonMenu.h \
		WdwMngr.h

moc_FindTrackDlg.o: moc_FindTrackDlg.cpp  FindTrackDlg.h StdAfx.h \
		SKMessageBox.h \
		CommonFiles/CommonObject.h \
		CommonFiles/CommonMenu.h \
		CommonFiles/Templ.h \
		WdwMngr.h

moc_FlSelect.o: moc_FlSelect.cpp  FlSelect.h 

moc_FlSelectOther.o: moc_FlSelectOther.cpp  FlSelectOther.h 

moc_HeightFilterDlg.o: moc_HeightFilterDlg.cpp  HeightFilterDlg.h 

moc_Runway.o: moc_Runway.cpp  Runway.h StdAfx.h \
		SKMessageBox.h \
		CommonFiles/CommonObject.h \
		CommonFiles/CommonMenu.h \
		CommonFiles/Templ.h \
		WdwMngr.h

moc_SaveAs.o: moc_SaveAs.cpp  SaveAs.h 

moc_SignIn.o: moc_SignIn.cpp  SignIn.h 

moc_SystemInfo.o: moc_SystemInfo.cpp  SystemInfo.h CommonDataTypes.h \
		StdAfx.h \
		SKMessageBox.h \
		CommonFiles/CommonObject.h \
		CommonFiles/CommonMenu.h \
		CommonFiles/Templ.h \
		WdwMngr.h

moc_TrackControl.o: moc_TrackControl.cpp  TrackControl.h 

moc_Tssr.o: moc_Tssr.cpp  Tssr.h 

moc_TssrOther.o: moc_TssrOther.cpp  TssrOther.h 

moc_Wtc.o: moc_Wtc.cpp  Wtc.h StdAfx.h \
		DataMngr.h \
		SKMessageBox.h \
		CommonFiles/CommonObject.h \
		CommonFiles/CommonMenu.h \
		CommonFiles/Templ.h \
		WdwMngr.h

moc_AsyncSocket.cpp: $(MOC) AsyncSocket.h
	$(MOC) AsyncSocket.h -o moc_AsyncSocket.cpp

moc_ImportantTrack.cpp: $(MOC) ImportantTrack.h
	$(MOC) ImportantTrack.h -o moc_ImportantTrack.cpp

moc_LineView.cpp: $(MOC) LineView.h
	$(MOC) LineView.h -o moc_LineView.cpp

moc_TopLevel.cpp: $(MOC) TopLevel.h
	$(MOC) TopLevel.h -o moc_TopLevel.cpp

moc_View.cpp: $(MOC) View.h
	$(MOC) View.h -o moc_View.cpp

moc_Ades.cpp: $(MOC) Ades.h
	$(MOC) Ades.h -o moc_Ades.cpp

moc_ArcTyp.cpp: $(MOC) ArcTyp.h
	$(MOC) ArcTyp.h -o moc_ArcTyp.cpp

moc_Assr.cpp: $(MOC) Assr.h
	$(MOC) Assr.h -o moc_Assr.cpp

moc_Brightness.cpp: $(MOC) Brightness.h
	$(MOC) Brightness.h -o moc_Brightness.cpp

moc_ChangePassword.cpp: $(MOC) ChangePassword.h
	$(MOC) ChangePassword.h -o moc_ChangePassword.cpp

moc_CustomSetDialog.cpp: $(MOC) CustomSetDialog.h
	$(MOC) CustomSetDialog.h -o moc_CustomSetDialog.cpp

moc_FindTrackDlg.cpp: $(MOC) FindTrackDlg.h
	$(MOC) FindTrackDlg.h -o moc_FindTrackDlg.cpp

moc_FlSelect.cpp: $(MOC) FlSelect.h
	$(MOC) FlSelect.h -o moc_FlSelect.cpp

moc_FlSelectOther.cpp: $(MOC) FlSelectOther.h
	$(MOC) FlSelectOther.h -o moc_FlSelectOther.cpp

moc_HeightFilterDlg.cpp: $(MOC) HeightFilterDlg.h
	$(MOC) HeightFilterDlg.h -o moc_HeightFilterDlg.cpp

moc_Runway.cpp: $(MOC) Runway.h
	$(MOC) Runway.h -o moc_Runway.cpp

moc_SaveAs.cpp: $(MOC) SaveAs.h
	$(MOC) SaveAs.h -o moc_SaveAs.cpp

moc_SignIn.cpp: $(MOC) SignIn.h
	$(MOC) SignIn.h -o moc_SignIn.cpp

moc_SystemInfo.cpp: $(MOC) SystemInfo.h
	$(MOC) SystemInfo.h -o moc_SystemInfo.cpp

moc_TrackControl.cpp: $(MOC) TrackControl.h
	$(MOC) TrackControl.h -o moc_TrackControl.cpp

moc_Tssr.cpp: $(MOC) Tssr.h
	$(MOC) Tssr.h -o moc_Tssr.cpp

moc_TssrOther.cpp: $(MOC) TssrOther.h
	$(MOC) TssrOther.h -o moc_TssrOther.cpp

moc_Wtc.cpp: $(MOC) Wtc.h
	$(MOC) Wtc.h -o moc_Wtc.cpp

####### Install

install:  

uninstall:  

